apiVersion: v1
kind: Service
metadata:
  name: player-service # This service name should match the name used in the FeignClient configuration of the team service
spec:
  selector:
    app: player-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP