apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service-with-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
        - name: team-service
          image: nadra187/team-service:1.3
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: microservice_db
            - name: DB_USER
              value: nadra187
            - name: DB_PASSWORD
              value: anything
          ports:
            - containerPort: 8081

