apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP   # default; only accessible within the cluster
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
