apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service-with-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
        - name: player-service
          image: nadra187/player-service:latest
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: mydb
            - name: DB_USER
              value: appuser
            - name: DB_PASSWORD
              value: apppass
          ports:
            - containerPort: 8080

